### ISSUE TITLE
SSO

### ISSUE THREAD

**Issue by underscope** [ExtensionEngine/tailor#632]
- [x] Implement OpenID Connect login (#652)
- [x] Move JWT token to cookie (#689)
- [x] Allow signup over OIDC (#697)
- [ ] Add silent auth over OIDC
- [ ] Allow OIDC Login branding
- [ ] Allow user management on IdP with adapters
- [ ] Implement discussed auth improvements
